/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Build */
        get: operations["get_build_api_v1_builds__build_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builds/{build_id}/artifacts/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_builds__build_id__artifacts__artifact_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_v1_config_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset local workspace */
        post: operations["reset_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Finding */
        patch: operations["patch_finding_api_v1_findings__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/analysis-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Project */
        post: operations["analyze_project_api_v1_projects__project_id__analysis_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Builds */
        get: operations["list_builds_api_v1_projects__project_id__builds_get"];
        put?: never;
        /** Create Build */
        post: operations["create_build_api_v1_projects__project_id__builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_projects__project_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_projects__project_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_v1_projects__project_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Project */
        post: operations["reset_project_api_v1_projects__project_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_projects__project_id__rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Summary */
        get: operations["project_summary_api_v1_projects__project_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tests */
        get: operations["list_tests_api_v1_projects__project_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/test-generation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Tests */
        post: operations["generate_tests_api_v1_projects__project_id__test_generation_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_v1_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_v1_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Rule */
        patch: operations["patch_rule_api_v1_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Rule */
        post: operations["approve_rule_api_v1_rules__rule_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Rule */
        post: operations["reject_rule_api_v1_rules__rule_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_v1_runs__run_id__reports_get"];
        put?: never;
        /** Make Report */
        post: operations["make_report_api_v1_runs__run_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_api_v1_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario-results/{result_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_v1_scenario_results__result_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Test */
        patch: operations["patch_test_api_v1_test_cases__test_case_id__patch"];
        trace?: never;
    };
    "/api/v1/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Waitlist
         * @description Record one privacy-minimal waitlist signup per authenticated identity.
         */
        post: operations["join_waitlist_api_v1_waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap Workspace */
        post: operations["bootstrap_workspace_api_v1_workspaces_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Personal Workspace */
        post: operations["reset_personal_workspace_api_v1_workspaces__workspace_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllCondition */
        "AllCondition-Input": {
            /** Conditions */
            conditions: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Input"] | components["schemas"]["AnyCondition-Input"] | components["schemas"]["NotCondition-Input"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "all";
        };
        /** AllCondition */
        "AllCondition-Output": {
            /** Conditions */
            conditions: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Output"] | components["schemas"]["AnyCondition-Output"] | components["schemas"]["NotCondition-Output"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "all";
        };
        /** AnyCondition */
        "AnyCondition-Input": {
            /** Conditions */
            conditions: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Input"] | components["schemas"]["AnyCondition-Input"] | components["schemas"]["NotCondition-Input"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "any";
        };
        /** AnyCondition */
        "AnyCondition-Output": {
            /** Conditions */
            conditions: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Output"] | components["schemas"]["AnyCondition-Output"] | components["schemas"]["NotCondition-Output"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "any";
        };
        /** ArmMetrics */
        ArmMetrics: {
            /** Attempted Violation Rate */
            attempted_violation_rate: number;
            /** Cases */
            cases: number;
            /** Cost */
            cost: number | null;
            /** Executed Violation Rate */
            executed_violation_rate: number;
            /** False Block Rate */
            false_block_rate: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Task Success Rate */
            task_success_rate: number;
            /** Tool Validation Error Rate */
            tool_validation_error_rate: number;
        };
        /** ArtifactContainsAssertion */
        ArtifactContainsAssertion: {
            /** Artifact */
            artifact: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "artifact_contains";
            /** Text */
            text: string;
        };
        /** ArtifactDigestAssertion */
        ArtifactDigestAssertion: {
            /** Artifact */
            artifact: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "artifact_digest";
            /** Sha256 */
            sha256: string;
        };
        /** Body_upload_document_api_v1_projects__project_id__documents_post */
        Body_upload_document_api_v1_projects__project_id__documents_post: {
            /** File */
            file?: string | null;
            /**
             * Kind
             * @default policy
             */
            kind: string;
            /** Name */
            name?: string | null;
            /** Text */
            text?: string | null;
        };
        /** BuildOut */
        BuildOut: {
            /** Artifacts */
            artifacts: {
                [key: string]: unknown;
            };
            /** Compiler Version */
            compiler_version: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Input Hash */
            input_hash: string;
            input_manifest: components["schemas"]["InputManifest"];
            /** Project Id */
            project_id: string;
            /** Source Map */
            source_map: {
                [key: string]: unknown;
            };
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /** CoverageDimension */
        CoverageDimension: {
            /** Covered Count */
            covered_count: number;
            /** Eligible Count */
            eligible_count: number;
            /** Ratio */
            ratio: number;
            /** Uncovered */
            uncovered: string[];
        };
        /** CoverageMetrics */
        CoverageMetrics: {
            /** Arms */
            arms: number;
            boundary_coverage: components["schemas"]["CoverageDimension"];
            /** Compiler Assertion Case Count */
            compiler_assertion_case_count: number;
            /** Compiler Assertion Coverage */
            compiler_assertion_coverage: number;
            /** Critical Unclassified Rules */
            critical_unclassified_rules: string[];
            /** Executable Case Count */
            executable_case_count: number;
            /** Explicit Assertion Case Count */
            explicit_assertion_case_count: number;
            /** Explicit Assertion Coverage */
            explicit_assertion_coverage: number;
            /** Positive Negative Boundary */
            positive_negative_boundary: boolean;
            rule_coverage: components["schemas"]["CoverageDimension"];
            source_coverage: components["schemas"]["CoverageDimension"];
            /** Tag Counts */
            tag_counts: {
                [key: string]: number;
            };
            /** Test Count */
            test_count: number;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Build Root Sha256 */
            build_root_sha256: string;
            /** Contains Customer Records */
            contains_customer_records: boolean;
            /** Data Scope */
            data_scope: string;
            /** Evaluation Timestamp */
            evaluation_timestamp: string;
            /** Facts Sha256 */
            facts_sha256: string;
            /** Facts Source */
            facts_source: string;
            /** Hash */
            hash: string;
            /** Name */
            name: string;
            /** Provenance */
            provenance: string;
            /** Runner Version */
            runner_version: string;
            /**
             * Schema Version
             * @default 0.3
             * @constant
             */
            schema_version: "0.3";
            /** Test Count */
            test_count: number;
            /** Tests Sha256 */
            tests_sha256: string;
            /** Tools Sha256 */
            tools_sha256: string;
            /** Version */
            version: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Line Count */
            line_count: number;
            /** Mime Type */
            mime_type: string;
            /** Name */
            name: string;
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Normalized Text */
            normalized_text: string;
            /** Origin */
            origin: {
                [key: string]: unknown;
            };
            /** Original Sha256 */
            original_sha256: string;
            /** Project Id */
            project_id: string;
            /** Token Estimate */
            token_estimate: number;
            /** Version */
            version: number;
        };
        /**
         * EmptyCondition
         * @description Explicitly validates the persisted empty condition used by human-only rules.
         */
        EmptyCondition: Record<string, never>;
        /** EvidenceFailure */
        EvidenceFailure: {
            /** Arm */
            arm: string;
            /** First Divergence */
            first_divergence: string | null;
            /** Test Id */
            test_id: string;
            /** Title */
            title: string;
        };
        /** EvidenceHashes */
        EvidenceHashes: {
            /** Artifacts */
            artifacts: {
                [key: string]: string;
            };
            /** Build Root Sha256 */
            build_root_sha256: string;
            /** Fact Fixture Sha256 */
            fact_fixture_sha256: string;
            /** Manifest Bytes Sha256 */
            manifest_bytes_sha256: string;
            /** Run Sha256 */
            run_sha256: string;
            /** Source Documents */
            source_documents: components["schemas"]["EvidenceSourceHash"][];
            /** Test Suite Sha256 */
            test_suite_sha256: string;
            /** Tests */
            tests: components["schemas"]["EvidenceTestHash"][];
            /** Tool Registry Sha256 */
            tool_registry_sha256: string;
        };
        /** EvidenceMetrics */
        EvidenceMetrics: {
            baseline_unenforced: components["schemas"]["ArmMetrics"];
            compiled_enforced: components["schemas"]["ArmMetrics"];
            compiled_unenforced: components["schemas"]["ArmMetrics"];
            coverage: components["schemas"]["CoverageMetrics"];
        };
        /** EvidenceProvenance */
        EvidenceProvenance: {
            /** Adapter */
            adapter: string;
            /** Compiler Version */
            compiler_version: string;
            /** Contains Customer Records */
            contains_customer_records: boolean;
            /** Data Scope */
            data_scope: string;
            /** Dataset */
            dataset: string;
            /** Dataset Manifest Sha256 */
            dataset_manifest_sha256: string;
            /** Evaluation Timestamp */
            evaluation_timestamp: string;
            /** Fixture Source */
            fixture_source: string;
            /** Model */
            model: string;
            /** Runner Version */
            runner_version: string;
            /** Test Count */
            test_count: number;
            /** Version */
            version: string;
        };
        /** EvidenceReport */
        EvidenceReport: {
            /** Comparison Arms */
            comparison_arms: string[];
            /** Deterministic Runtime Boundary */
            deterministic_runtime_boundary: string;
            /** Digest Definition */
            digest_definition: string;
            /** Evidence Boundary */
            evidence_boundary: string;
            fixture_provenance: components["schemas"]["FixtureProvenance"];
            hashes: components["schemas"]["EvidenceHashes"];
            /** Limitations */
            limitations: string[];
            metrics: components["schemas"]["EvidenceMetrics"];
            provenance: components["schemas"]["EvidenceProvenance"];
            /** Report Digest */
            report_digest: string;
            /**
             * Schema Version
             * @default 0.3
             * @constant
             */
            schema_version: "0.3";
            /** Test Count */
            test_count: number;
            /** Top Failures */
            top_failures: components["schemas"]["EvidenceFailure"][];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "Changes required" | "Fixture suite passed";
        };
        /** EvidenceSourceHash */
        EvidenceSourceHash: {
            /** Name */
            name: string;
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Normalizer */
            normalizer: string;
            /** Normalizer Version */
            normalizer_version: string;
            /** Original Sha256 */
            original_sha256: string;
            /** Parser */
            parser: string;
            /** Parser Version */
            parser_version: string;
            /** Version */
            version: number;
        };
        /** EvidenceTestHash */
        EvidenceTestHash: {
            /** Spec Sha256 */
            spec_sha256: string;
            /** Stable Key */
            stable_key: string;
        };
        /** ExpectedOutcome */
        ExpectedOutcome: {
            /** Assertions */
            assertions?: (components["schemas"]["ArtifactContainsAssertion"] | components["schemas"]["FindingAssertion"] | components["schemas"]["ArtifactDigestAssertion"])[];
            /** Forbidden Executed Tools */
            forbidden_executed_tools?: string[];
            /**
             * Guarded Decision
             * @enum {string}
             */
            guarded_decision: "allow" | "deny" | "require_approval" | "require_prior_event" | "indeterminate" | "not_applicable";
            /** Task Outcome */
            task_outcome: string;
        };
        /** FindingAssertion */
        FindingAssertion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "finding";
            /** Related Rules */
            related_rules: string[];
            /**
             * Resolution State
             * @enum {string}
             */
            resolution_state: "open" | "resolved" | "accepted_risk";
            /** Type */
            type: string;
        };
        /** FindingOut */
        FindingOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Project Id */
            project_id: string;
            /** Proof Status */
            proof_status: string;
            /** Related Rule Ids */
            related_rule_ids: string[];
            /** Resolution Note */
            resolution_note: string;
            /** Resolution State */
            resolution_state: string;
            /** Severity */
            severity: string;
            /** Type */
            type: string;
            /** Witness */
            witness: {
                [key: string]: unknown;
            };
        };
        /** FindingPatch */
        FindingPatch: {
            /** Authority */
            authority?: string | null;
            /**
             * Expected Resolution State
             * @default open
             * @enum {string}
             */
            expected_resolution_state: "open" | "resolved" | "accepted_risk";
            /** Loser Rule Id */
            loser_rule_id?: string | null;
            /**
             * Resolution Note
             * @default
             */
            resolution_note: string;
            /**
             * Resolution State
             * @enum {string}
             */
            resolution_state: "open" | "resolved" | "accepted_risk";
            /** Winner Rule Id */
            winner_rule_id?: string | null;
        };
        /** FixtureProvenance */
        FixtureProvenance: {
            facts: components["schemas"]["ManifestFactInput"];
            tests: components["schemas"]["FixtureTestProvenance"];
            tools: components["schemas"]["ManifestArtifactInput"];
        };
        /** FixtureTestProvenance */
        FixtureTestProvenance: {
            /** Data Scope */
            data_scope: string;
            /** Name */
            name: string;
            /** Provenance */
            provenance: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputManifest */
        InputManifest: {
            compiler: components["schemas"]["ManifestCompiler"];
            facts: components["schemas"]["ManifestFactInput"];
            findings: components["schemas"]["ManifestFindings"];
            /** Rules */
            rules: components["schemas"]["ManifestRuleInput"][];
            runtime: components["schemas"]["ManifestRuntime"];
            /**
             * Schema Version
             * @default 0.3
             * @constant
             */
            schema_version: "0.3";
            /** Sources */
            sources: components["schemas"]["ManifestSourceInput"][];
            /** Tests */
            tests: components["schemas"]["ManifestTestInput"][];
            tools: components["schemas"]["ManifestArtifactInput"];
        };
        /** ManifestArtifactInput */
        ManifestArtifactInput: {
            /** Artifact */
            artifact: string;
            /** Artifact Sha256 */
            artifact_sha256: string;
            /** Source */
            source: string;
            /** Source Sha256 */
            source_sha256: string;
        };
        /** ManifestCompiler */
        ManifestCompiler: {
            /** Name */
            name: string;
            /** Serialization */
            serialization: string;
            /** Token Estimator */
            token_estimator: string;
            /** Version */
            version: string;
        };
        /** ManifestFactInput */
        ManifestFactInput: {
            /** Artifact */
            artifact: string;
            /** Artifact Sha256 */
            artifact_sha256: string;
            /** Contains Customer Records */
            contains_customer_records: boolean;
            /** Data Scope */
            data_scope: string;
            /** Source */
            source: string;
            /** Source Sha256 */
            source_sha256: string;
        };
        /** ManifestFinding */
        ManifestFinding: {
            /** Message */
            message: string;
            /** Proof Status */
            proof_status: string;
            /** Related Rules */
            related_rules: string[];
            /** Resolution Note */
            resolution_note: string;
            /**
             * Resolution State
             * @enum {string}
             */
            resolution_state: "open" | "resolved" | "accepted_risk";
            /** Severity */
            severity: string;
            /** Type */
            type: string;
            /** Witness */
            witness: {
                [key: string]: unknown;
            };
        };
        /** ManifestFindings */
        ManifestFindings: {
            /** Accepted */
            accepted: components["schemas"]["ManifestFinding"][];
            /** Unresolved */
            unresolved: components["schemas"]["ManifestFinding"][];
        };
        /** ManifestRuleInput */
        ManifestRuleInput: {
            /**
             * Category
             * @enum {string}
             */
            category: "style" | "workflow" | "knowledge" | "runtime_fact" | "hard_constraint" | "handoff" | "quality";
            /** Digest */
            digest: string;
            /**
             * Enforcement
             * @enum {string}
             */
            enforcement: "prompt" | "guard" | "test_only" | "human_review";
            /** Revision */
            revision: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** Source Documents */
            source_documents: string[];
            /** Stable Key */
            stable_key: string;
            /** Status */
            status: string;
        };
        /** ManifestRuntime */
        ManifestRuntime: {
            /** Adapter */
            adapter: string;
            /** Arms */
            arms: string[];
            /** Domain */
            domain: string;
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "pre_tool" | "post_tool" | "conversation" | "offline";
            /** Policy Schema Version */
            policy_schema_version: string;
            /** Runner Input Version */
            runner_input_version: string;
        };
        /** ManifestSourceInput */
        ManifestSourceInput: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Normalizer */
            normalizer: string;
            /** Normalizer Version */
            normalizer_version: string;
            /** Original Sha256 */
            original_sha256: string;
            /** Parser */
            parser: string;
            /** Parser Version */
            parser_version: string;
            /** Version */
            version: number;
        };
        /** ManifestTestInput */
        ManifestTestInput: {
            /** Digest */
            digest: string;
            /** Provenance */
            provenance: string;
            /** Rule Ids */
            rule_ids: string[];
            /** Stable Key */
            stable_key: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string | null;
            /** Id */
            id: string;
            /** Is Anonymous */
            is_anonymous: boolean;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceOut"][];
        };
        /** NotCondition */
        "NotCondition-Input": {
            /** Condition */
            condition: components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Input"] | components["schemas"]["AnyCondition-Input"] | components["schemas"]["NotCondition-Input"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "not";
        };
        /** NotCondition */
        "NotCondition-Output": {
            /** Condition */
            condition: components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Output"] | components["schemas"]["AnyCondition-Output"] | components["schemas"]["NotCondition-Output"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "not";
        };
        /** OperationError */
        OperationError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** OperationOut */
        OperationOut: {
            /** Attempt Count */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error?: components["schemas"]["OperationError"] | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Max Attempts */
            max_attempts: number;
            /** Progress */
            progress: number;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: ("build" | "run" | "project") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "dead_lettered" | "cancelled";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** PolicyEvent */
        PolicyEvent: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Type */
            type: string;
        };
        /** Predicate */
        Predicate: {
            /** Fact */
            fact: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "predicate";
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "in" | "not_in" | "exists" | "contains" | "regex";
            /** Value */
            value?: unknown;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Domain
             * @default retail
             */
            domain: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** ReportOut */
        ReportOut: {
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            evidence: components["schemas"]["EvidenceReport"];
            /** Id */
            id: string;
            /** Rendered Markdown */
            rendered_markdown: string;
            /** Run Id */
            run_id: string;
            /** Verdict */
            verdict: string;
        };
        /** RuleException */
        "RuleException-Input": {
            /** Condition */
            condition: components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Input"] | components["schemas"]["AnyCondition-Input"] | components["schemas"]["NotCondition-Input"];
            /**
             * Effect
             * @default not_applicable
             * @enum {string}
             */
            effect: "allow" | "not_applicable";
            /** Reason */
            reason: string;
        };
        /** RuleException */
        "RuleException-Output": {
            /** Condition */
            condition: components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Output"] | components["schemas"]["AnyCondition-Output"] | components["schemas"]["NotCondition-Output"];
            /**
             * Effect
             * @default not_applicable
             * @enum {string}
             */
            effect: "allow" | "not_applicable";
            /** Reason */
            reason: string;
        };
        /** RuleOut */
        RuleOut: {
            /**
             * Category
             * @enum {string}
             */
            category: "style" | "workflow" | "knowledge" | "runtime_fact" | "hard_constraint" | "handoff" | "quality";
            /** Condition */
            condition: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Output"] | components["schemas"]["AnyCondition-Output"] | components["schemas"]["NotCondition-Output"]) | components["schemas"]["EmptyCondition"];
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Decidability
             * @enum {string}
             */
            decidability: "machine_decidable" | "model_judged" | "human";
            /**
             * Effect
             * @enum {string}
             */
            effect: "allow" | "deny" | "require_approval" | "require_prior_event" | "observe_only";
            /**
             * Enforcement
             * @enum {string}
             */
            enforcement: "prompt" | "guard" | "test_only" | "human_review";
            /** Exceptions */
            exceptions: components["schemas"]["RuleException-Output"][];
            /** Id */
            id: string;
            /** Normative Text */
            normative_text: string;
            /** Project Id */
            project_id: string;
            /** Requires */
            requires: components["schemas"]["RuleRequirement"][];
            /** Reviewer Note */
            reviewer_note: string;
            /** Revision */
            revision: number;
            scope: components["schemas"]["RuleScope"];
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** Source Refs */
            source_refs: components["schemas"]["SourceRef"][];
            /** Stable Key */
            stable_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "candidate" | "needs_review" | "approved" | "rejected" | "superseded";
            /** Target Tools */
            target_tools: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RulePatch */
        RulePatch: {
            /** Condition */
            condition?: (components["schemas"]["Predicate"] | components["schemas"]["AllCondition-Input"] | components["schemas"]["AnyCondition-Input"] | components["schemas"]["NotCondition-Input"]) | components["schemas"]["EmptyCondition"] | null;
            /** Decidability */
            decidability?: ("machine_decidable" | "model_judged" | "human") | null;
            /** Effect */
            effect?: ("allow" | "deny" | "require_approval" | "require_prior_event" | "observe_only") | null;
            /** Enforcement */
            enforcement?: ("prompt" | "guard" | "test_only" | "human_review") | null;
            /** Exceptions */
            exceptions?: components["schemas"]["RuleException-Input"][] | null;
            /** Expected Revision */
            expected_revision: number;
            /** Normative Text */
            normative_text?: string | null;
            /** Requires */
            requires?: components["schemas"]["RuleRequirement"][] | null;
            /** Reviewer Note */
            reviewer_note?: string | null;
            scope?: components["schemas"]["RuleScope"] | null;
            /** Target Tools */
            target_tools?: string[] | null;
            /** Title */
            title?: string | null;
        };
        /** RuleRequirement */
        RuleRequirement: {
            /** Event Type */
            event_type?: string | null;
            /** Fact */
            fact?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "prior_event" | "approval" | "fact";
            /** Match Arguments */
            match_arguments?: string[];
            /** Op */
            op?: ("eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "in" | "not_in" | "exists" | "contains" | "regex") | null;
            /** Value */
            value?: unknown;
        };
        /** RuleReview */
        RuleReview: {
            /** Expected Revision */
            expected_revision: number;
            /** Reviewer Note */
            reviewer_note?: string | null;
        };
        /** RuleScope */
        RuleScope: {
            /** Domain */
            domain: string;
            /**
             * Lifecycle
             * @default pre_tool
             * @enum {string}
             */
            lifecycle: "pre_tool" | "post_tool" | "conversation" | "offline";
            /** Tools */
            tools?: string[];
        };
        /** RunCreate */
        RunCreate: {
            /** Build Id */
            build_id?: string | null;
        };
        /** RunOut */
        RunOut: {
            /** Adapter */
            adapter: string;
            /** Build Id */
            build_id: string;
            dataset_manifest: components["schemas"]["DatasetManifest"];
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Model */
            model: string | null;
            /** Project Id */
            project_id: string;
            /** Requested Arms */
            requested_arms: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** ScriptedTrajectories */
        ScriptedTrajectories: {
            /** Baseline Unenforced */
            baseline_unenforced?: components["schemas"]["ToolCallStep"][];
            /** Compiled Enforced */
            compiled_enforced?: components["schemas"]["ToolCallStep"][];
            /** Compiled Unenforced */
            compiled_unenforced?: components["schemas"]["ToolCallStep"][];
        };
        /** SourceRef */
        SourceRef: {
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name?: string | null;
            /** Line End */
            line_end: number;
            /** Line Start */
            line_start: number;
            /** Quote */
            quote: string;
            /** Source Sha256 */
            source_sha256: string;
        };
        /** TestCaseOut */
        TestCaseOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Provenance */
            provenance: string;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "approved" | "needs_review" | "rejected";
            spec: components["schemas"]["TestCaseSpec"];
            /** Stable Key */
            stable_key: string;
            /** Title */
            title: string;
        };
        /** TestCasePatch */
        TestCasePatch: {
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "approved" | "needs_review" | "rejected";
        };
        /** TestCaseSpec */
        TestCaseSpec: {
            /** Events */
            events?: components["schemas"]["PolicyEvent"][];
            expected: components["schemas"]["ExpectedOutcome"];
            /** Id */
            id: string;
            /** Initial State */
            initial_state: {
                [key: string]: unknown;
            };
            /** Messages */
            messages: components["schemas"]["TestMessage"][];
            /** Provenance */
            provenance: string;
            /** Rule Ids */
            rule_ids: string[];
            /**
             * Schema Version
             * @default 0.2
             * @enum {string}
             */
            schema_version: "0.1" | "0.2";
            scripted_trajectories: components["schemas"]["ScriptedTrajectories"];
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
        };
        /** TestMessage */
        TestMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
        };
        /** ToolCallStep */
        ToolCallStep: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Type
             * @default tool_call
             * @constant
             */
            type: "tool_call";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WaitlistCreate */
        WaitlistCreate: {
            /** Email */
            email: string;
        };
        /** WaitlistOut */
        WaitlistOut: {
            /**
             * Joined
             * @default true
             * @constant
             */
            joined: true;
        };
        /** WorkspaceBootstrap */
        WorkspaceBootstrap: {
            /**
             * Name
             * @default My workspace
             */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /** WorkspaceBootstrapOut */
        WorkspaceBootstrapOut: {
            /** Created */
            created: boolean;
            project: components["schemas"]["ProjectOut"];
            workspace: components["schemas"]["WorkspaceOut"];
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_build_api_v1_builds__build_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_builds__build_id__artifacts__artifact_path__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                build_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_config_api_v1_config_public_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_workspace: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-reset-secret"?: string | null;
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_finding_api_v1_findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_project_api_v1_projects__project_id__analysis_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_builds_api_v1_projects__project_id__builds_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_build_api_v1_projects__project_id__builds_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_projects__project_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_projects__project_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_projects__project_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_projects__project_id__findings_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_project_api_v1_projects__project_id__reset_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_projects__project_id__rules_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_summary_api_v1_projects__project_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tests_api_v1_projects__project_id__test_cases_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_tests_api_v1_projects__project_id__test_generation_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_v1_reports__report_id__export_get: {
        parameters: {
            query: {
                format: string;
            };
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_v1_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_rule_api_v1_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_rule_api_v1_rules__rule_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_rule_api_v1_rules__rule_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_runs__run_id__reports_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_report_api_v1_runs__run_id__reports_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_v1_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_v1_scenario_results__result_id__trace_get: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_test_api_v1_test_cases__test_case_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCasePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_api_v1_waitlist_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_workspace_api_v1_workspaces_bootstrap_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceBootstrap"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceBootstrapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_personal_workspace_api_v1_workspaces__workspace_id__reset_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aletheia-origin-token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
